version: "3.3"

services:
    
    BestPlayzBackend:
        environment:
            EnvironmentName: Production
        ports:
            - 4701:80
    BestPlayzFrontend:
        environment:
            EnvironmentName: Production
        ports:
            - 4601:80
           

