version: "3"
services:
    frontend:
        image: nadiamiteva/BestPlayzFrontend:${BUILD_NUMBER}
        restart: always
    backend:
        image: nadiamiteva/BestPlayzBackend:${BUILD_NUMBER}
        restart: always
    postgres:
        container_name: postgres
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - /data/postgres:/data/postgres
        env_file:
            - ./BestPlayzBackend/docker.env
        networks:
            - postgres
    pgadmin:
        links:
         - postgres:postgres
        container_name: best-playz-pgadmin
        image: dpage/pgadmin4
        ports:
        - "8083:80"
        volumes:
        - /data/pgadmin:/root/.pgadmin
        env_file:
        - docker.env
        networks:
        - postgres
                    
networks:
    postgres:
        driver: bridge
